---
title: "wafergen"
output: 
  html_document:
    toc: true
    toc_float: true
---

#### Jin Choi, Apr 22, 2019
# Wafergen analysis
This site shows how to analyze wafergen data

### Load Library
```{r}
library(reshape2)
library(ggplot2)
library(ggpubr)
```

### Read data
```{r}
#read data 
chip1 <- read.table("../data/Jin061518.txt", sep="\t", header=T)[,c("Assay","Sample","Ct")]
dat <- chip1
#get sample info
meta <- read.csv("../data/meta_NPB.csv")

#standard
meta_std <- read.csv("../data/meta_standard_NPB.csv")
```


### Read function
```{r}
#########################
# function
########################
add_to_meta <- function(merged_meta_chip, chip, target, meta, meta_std, name_target, sample_id){
	sub <- subset(chip, Assay %in% target)
	casted <- dcast(sub, Sample~Assay, fun=mean, value.var = "Ct", na.rm=T)
	merged_meta <- merge(merged_meta_chip, casted, by.x = sample_id, by.y="Sample")
	meta_sub <- subset(meta_std, Assay %in% name_target)
	data_sub <- subset(sub, Sample %in% meta_sub$Sample)
	merged_std <- merge(data_sub, meta_sub, by.x = "Sample", by.y = "Sample", all.x=T)
	merged_std_no_NA <- subset(merged_std, Ct != "NA")
	quality_filtered <- subset(merged_std_no_NA, count > 10)
	ct <- quality_filtered$Ct 
	count <-  log10(quality_filtered$count+1)
	lm.r <- lm(ct ~ count)
	coef <- coef(lm.r)[2]
	eff <- 100*((10^(-1/coef))-1)
	inverse.lm <- lm(count ~ ct)
	
	if (length(target) > 1){
		merged_meta$mean_target<- rowMeans(merged_meta[,target], na.rm=T)
		val = merged_meta$"mean_target"
	}else{
		val = merged_meta[,name_target]
	}
	
	merged_meta$temp<- 10^predict(inverse.lm ,data.frame(ct = val), interval = "predict")[,1]
	names(merged_meta)[ncol(merged_meta)] <- paste0("cal_", name_target)
	names(merged_meta)[ncol(merged_meta)-1] <- paste0("mean_", name_target)
	return(merged_meta)
}
```

### Run functions with four target genes
```{r}
###############
# Add 16S rRNA count
###############
name_target = "16s"
sample_id = "sample"
target <- c("16sTom1","16sTom2","16sTom3")
merged_meta <- add_to_meta(meta, dat, target, meta, meta_std, name_target, sample_id)

#########################
# Add ermB count
########################
name_target = "ermb"
sample_id = "sample"
target <- c("ermbEdBob1","ermbEdBob2","ermbEdBob3")
merged_meta <- add_to_meta(merged_meta, dat, target, meta, meta_std, name_target, sample_id)

#########################
# Add ermF count
########################
name_target = "ermf"
sample_id = "sample"
target <- c("ermfEdBob1","ermfEdBob2","ermfEdBob3")
merged_meta <- add_to_meta(merged_meta, dat, target, meta, meta_std, name_target, sample_id)

#########################
# Add tetM count
########################
name_target = "tetm"
sample_id = "sample"
target <- c("tetmBob1","tetmBob2","tetmBob3")
merged_meta <- add_to_meta(merged_meta, dat, target, meta, meta_std, name_target, sample_id)
```
